perceptron:
	javac lc/example/PerceptronClassifierTest.java
	java lc.example.PerceptronClassifierTest earthquake-noisy.data.txt 1000 0

logistic:
	javac lc/example/LogisticClassifierTest.java
	java lc.example.LogisticClassifierTest earthquake-noisy.data.txt 1000 0
