decisionTreeAIMA:
	javac dt/example/WillWaitProblem.java
	java dt.example.WillWaitProblem WillWait-data.txt
decisionTreeIris:
	javac dt/example/Iris.java
	java dt.example.Iris iris.data.discrete.txt

perceptron:
	javac lc/example/PerceptronClassifierTest.java
	java lc.example.PerceptronClassifierTest earthquake-noisy.data.txt 1000 0

logistic:
	javac lc/example/LogisticClassifierTest.java
	java lc.example.LogisticClassifierTest earthquake-noisy.data.txt 1000 0
